# Generated by Django 3.1.6 on 2021-02-05 21:05

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('start_bid', models.FloatField()),
                ('image', models.URLField()),
                ('created', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.IntegerField()),
                ('new_bid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='auctions',
            field=models.JSONField(default=auctions.models.my_default),
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.JSONField(default=auctions.models.my_default),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.JSONField(default=auctions.models.my_default),
        ),
    ]
