# Generated by Django 3.1.6 on 2021-03-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210205_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
