# Generated by Django 3.1.6 on 2021-03-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210325_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='createdBy',
        ),
    ]
