# Generated by Django 3.1.6 on 2021-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='createdBy',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
