# Generated by Django 3.1.6 on 2021-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210326_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction_category',
            name='listing',
        ),
        migrations.AddField(
            model_name='auction_category',
            name='category_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_category',
            name='listing_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
