# Generated by Django 3.1.6 on 2021-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210326_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
